baseURL = "https://air-factories-2-0.github.io/af2-website/public/"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "it"
[languages]

  [languages.en]
    title = "Air Factories 2.0"
    contentDir = 'content/en'
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = 'Italian'
        url = ''
        pre = "btn site-menu-lang"

      [[languages.en.menu.main]]
        name = 'Gallery'
        url = 'gallery'
        weight = -110
        pre = "btn site-menu-gallery"


  [languages.it]
    title = "Air Factories 2.0"
    contentDir = 'content/it'

       [languages.it.menu]
        [[languages.it.menu.main]]
          name = 'English'
          url = 'en'
          pre = "btn site-menu-lang"


        [[languages.it.menu.main]]
          name = 'Galleria'
          url = 'galleria'
          weight = -110
          pre = "btn site-menu-gallery"


  #Modo semplice per mantere lo stesso tema su più pagine è fare finta che sia una lingua
  [languages.gallery]
    title = "Air Factories 2.0 Gallery "
    contentDir = 'content/en/gallery'
      [languages.gallery.menu]
      [[languages.gallery.menu.main]]
        name = 'Home'
        url = 'en'
        pre = "btn site-menu-lang"

  [languages.galleria]
    title = "Galleria Air Factories 2.0"
    contentDir = 'content/it/galleria'
      [languages.galleria.menu]
      [[languages.galleria.menu.main]]
        name = 'Home'
        url = ''
        pre = "btn site-menu-lang"



# The "title" of your website
title = "Air Factories 2.0"

[params]
    copyright = "© Air Factories 2.0"

    description = ""

    favicon = "images/favicon.png"

    images = ["images/cover-image.jpg"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Air Factories 2.0"


    [params.meta]
        keywords = "3D, printer, blockchain, ethereum, distributed app, dapp, factories, air factories"
